# Generated by Django 6.0.4 on 2026-04-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('places', '0002_region_full_name_region_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='参考价格'),
        ),
        migrations.AlterField(
            model_name='food',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='所属城镇乡村'),
        ),
    ]
