# Generated by Django 6.0.4 on 2026-04-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_price_alter_food_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='content',
            field=models.TextField(blank=True, help_text='正文详情/富文本内容', verbose_name='详细内容'),
        ),
    ]
