# Generated by Django 6.0.4 on 2026-04-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('places', '0002_region_full_name_region_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='所属城镇乡村'),
        ),
    ]
