# Generated by Django 6.0.4 on 2026-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='用于列表、版面受限处', max_length=200, verbose_name='标题(简称)')),
                ('full_title', models.CharField(blank=True, help_text='用于详情页展示', max_length=200, verbose_name='全称')),
                ('summary', models.TextField(blank=True, help_text='详情页顶部的导语/特色说明', verbose_name='内容概述')),
                ('level_tag', models.CharField(blank=True, help_text='右上角突出显示的标签，如：非遗级别、口气、菜系等', max_length=50, verbose_name='级别/品别标签')),
                ('feature_tags', models.CharField(blank=True, help_text='多个请用逗号隔开，如：亲子,观海,小火车', max_length=255, verbose_name='特色标签云')),
                ('image', models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='焦点图')),
                ('image_show_watermark', models.BooleanField(default=False, verbose_name='详情页显示水印')),
                ('watermark_pos', models.CharField(choices=[('center', '居中'), ('bottom_center', '底部中间'), ('bottom_right', '右下角')], default='bottom_right', max_length=20, verbose_name='水印位置')),
                ('source', models.CharField(blank=True, help_text='如：百度、官方提供', max_length=100, verbose_name='内容来源')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者/贡献者')),
                ('publish_date', models.DateField(blank=True, help_text='前台显示的自定义日期', null=True, verbose_name='显示日期')),
                ('redirect_url', models.URLField(blank=True, help_text='填写后直接跳转', verbose_name='跳转链接')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sticky_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_home', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏屏蔽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL标识')),
            ],
            options={
                'verbose_name': '资讯·动态',
                'verbose_name_plural': '资讯·动态',
            },
        ),
    ]
