# Generated by Django 6.0.4 on 2026-04-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='全称'),
        ),
        migrations.AddField(
            model_name='region',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='区域介绍'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='spot_type',
            field=models.CharField(choices=[('scenic', '景区'), ('checkin', '打卡点')], default='scenic', max_length=20, verbose_name='地点类型'),
        ),
        migrations.AlterField(
            model_name='scenicspot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='所属城镇乡村'),
        ),
    ]
