# Generated by Django 6.0.4 on 2026-04-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_region_full_name_region_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=models.TextField(blank=True, help_text='正文详情/富文本内容', verbose_name='详细内容'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='content',
            field=models.TextField(blank=True, help_text='正文详情/富文本内容', verbose_name='详细内容'),
        ),
        migrations.AddField(
            model_name='traffic',
            name='content',
            field=models.TextField(blank=True, help_text='正文详情/富文本内容', verbose_name='详细内容'),
        ),
    ]
