# Generated by Django 6.0.4 on 2026-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题/主题')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact', models.CharField(blank=True, help_text='电话、邮箱或微信', max_length=100, verbose_name='联系方式')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '互动信息',
                'verbose_name_plural': '互动信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
