# Generated by Django 6.0.4 on 2026-04-14 02:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='关于我们'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='联系我们'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='cooperation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='合作事宜'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='service',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='服务协议'),
        ),
    ]
