# Generated by Django 6.0.4 on 2026-04-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content'),
        ('places', '0003_place_content_scenicspot_content_traffic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place', verbose_name='关联目的地'),
        ),
    ]
