# Generated by Django 6.0.4 on 2026-04-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelogue',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='作者/贡献者'),
        ),
        migrations.AlterField(
            model_name='travelogue',
            name='content',
            field=models.TextField(blank=True, help_text='正文详情/富文本内容', verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='travelogue',
            name='slug',
            field=models.CharField(help_text='系统自动生成：YYYYMMDDHHmm格式', max_length=20, unique=True, verbose_name='URL码'),
        ),
        migrations.AlterField(
            model_name='travelogue',
            name='source',
            field=models.CharField(blank=True, help_text='如：百度、官方提供', max_length=100, verbose_name='内容来源'),
        ),
    ]
