# Generated by Django 6.0.4 on 2026-04-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域',
                'ordering': ['-sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='用于列表、版面受限处', max_length=200, verbose_name='标题(简称)')),
                ('full_title', models.CharField(blank=True, help_text='用于详情页展示', max_length=200, verbose_name='全称')),
                ('summary', models.TextField(blank=True, help_text='详情页顶部的导语/特色说明', verbose_name='内容概述')),
                ('level_tag', models.CharField(blank=True, help_text='右上角突出显示的标签，如：非遗级别、口气、菜系等', max_length=50, verbose_name='级别/品别标签')),
                ('feature_tags', models.CharField(blank=True, help_text='多个请用逗号隔开，如：亲子,观海,小火车', max_length=255, verbose_name='特色标签云')),
                ('image', models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='焦点图')),
                ('image_show_watermark', models.BooleanField(default=False, verbose_name='详情页显示水印')),
                ('watermark_pos', models.CharField(choices=[('center', '居中'), ('bottom_center', '底部中间'), ('bottom_right', '右下角')], default='bottom_right', max_length=20, verbose_name='水印位置')),
                ('source', models.CharField(blank=True, help_text='如：百度、官方提供', max_length=100, verbose_name='内容来源')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者/贡献者')),
                ('publish_date', models.DateField(blank=True, help_text='前台显示的自定义日期', null=True, verbose_name='显示日期')),
                ('redirect_url', models.URLField(blank=True, help_text='填写后直接跳转', verbose_name='跳转链接')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sticky_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_home', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏屏蔽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('english_code', models.SlugField(help_text='用于URL路由，如: hangzhou', max_length=100, unique=True, verbose_name='英文标识(Slug)')),
                ('alias', models.CharField(blank=True, help_text='如: 泉城', max_length=100, verbose_name='别名')),
                ('best_time', models.CharField(blank=True, help_text='如: 4月-10月', max_length=200, verbose_name='最佳游玩时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_places', to='places.place', verbose_name='上级城乡')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.region', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '城乡/街巷',
                'verbose_name_plural': '城乡/街巷',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='用于列表、版面受限处', max_length=200, verbose_name='标题(简称)')),
                ('full_title', models.CharField(blank=True, help_text='用于详情页展示', max_length=200, verbose_name='全称')),
                ('summary', models.TextField(blank=True, help_text='详情页顶部的导语/特色说明', verbose_name='内容概述')),
                ('level_tag', models.CharField(blank=True, help_text='右上角突出显示的标签，如：非遗级别、口气、菜系等', max_length=50, verbose_name='级别/品别标签')),
                ('feature_tags', models.CharField(blank=True, help_text='多个请用逗号隔开，如：亲子,观海,小火车', max_length=255, verbose_name='特色标签云')),
                ('image', models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='焦点图')),
                ('image_show_watermark', models.BooleanField(default=False, verbose_name='详情页显示水印')),
                ('watermark_pos', models.CharField(choices=[('center', '居中'), ('bottom_center', '底部中间'), ('bottom_right', '右下角')], default='bottom_right', max_length=20, verbose_name='水印位置')),
                ('source', models.CharField(blank=True, help_text='如：百度、官方提供', max_length=100, verbose_name='内容来源')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者/贡献者')),
                ('publish_date', models.DateField(blank=True, help_text='前台显示的自定义日期', null=True, verbose_name='显示日期')),
                ('redirect_url', models.URLField(blank=True, help_text='填写后直接跳转', verbose_name='跳转链接')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sticky_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_home', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏屏蔽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('english_code', models.SlugField(help_text='用于URL路由', max_length=100, unique=True, verbose_name='英文标识(Slug)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='详细地址')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='开放时间')),
                ('ticket_info', models.CharField(blank=True, max_length=200, verbose_name='门票信息')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='所属城乡')),
            ],
            options={
                'verbose_name': '打卡地/景区',
                'verbose_name_plural': '打卡地/景区',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='用于列表、版面受限处', max_length=200, verbose_name='标题(简称)')),
                ('full_title', models.CharField(blank=True, help_text='用于详情页展示', max_length=200, verbose_name='全称')),
                ('summary', models.TextField(blank=True, help_text='详情页顶部的导语/特色说明', verbose_name='内容概述')),
                ('level_tag', models.CharField(blank=True, help_text='右上角突出显示的标签，如：非遗级别、口气、菜系等', max_length=50, verbose_name='级别/品别标签')),
                ('feature_tags', models.CharField(blank=True, help_text='多个请用逗号隔开，如：亲子,观海,小火车', max_length=255, verbose_name='特色标签云')),
                ('image', models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='焦点图')),
                ('image_show_watermark', models.BooleanField(default=False, verbose_name='详情页显示水印')),
                ('watermark_pos', models.CharField(choices=[('center', '居中'), ('bottom_center', '底部中间'), ('bottom_right', '右下角')], default='bottom_right', max_length=20, verbose_name='水印位置')),
                ('source', models.CharField(blank=True, help_text='如：百度、官方提供', max_length=100, verbose_name='内容来源')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者/贡献者')),
                ('publish_date', models.DateField(blank=True, help_text='前台显示的自定义日期', null=True, verbose_name='显示日期')),
                ('redirect_url', models.URLField(blank=True, help_text='填写后直接跳转', verbose_name='跳转链接')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sticky_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_home', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏屏蔽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('traffic_type', models.CharField(help_text='如: 高铁, 飞机, 自驾', max_length=50, verbose_name='交通方式')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='耗时/说明')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='目的地城乡')),
            ],
            options={
                'verbose_name': '交通出行',
                'verbose_name_plural': '交通出行',
            },
        ),
    ]
