# Generated by Django 6.0.4 on 2026-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTextRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='推荐标题')),
                ('url', models.URLField(verbose_name='跳转链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页文字推荐',
                'verbose_name_plural': '首页文字推荐',
                'ordering': ['-sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='关键词')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '搜索关键词',
                'verbose_name_plural': '搜索关键词',
                'ordering': ['-sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='关于我们')),
                ('service', models.TextField(blank=True, verbose_name='服务协议')),
                ('contact', models.TextField(blank=True, verbose_name='联系我们')),
                ('cooperation', models.TextField(blank=True, verbose_name='合作事宜')),
                ('copyright', models.TextField(blank=True, verbose_name='版权信息(底部)')),
                ('copyright_home', models.TextField(blank=True, verbose_name='首页专用版权信息')),
            ],
            options={
                'verbose_name': '网站基本信息',
                'verbose_name_plural': '网站基本信息',
            },
        ),
    ]
