# Generated by Django 6.0.4 on 2026-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteinfo_about_alter_siteinfo_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source_url',
            field=models.URLField(blank=True, help_text='用户提交反馈时的页面地址', verbose_name='来源页面'),
        ),
    ]
